### ISSUE TITLE
[menu-button]: Add an alternative to focus-visible

### ISSUE THREAD

**Issue by sandrina-p** [reach/reach-ui#793]
### Current Behavior

In the menu-button, is not possible to style the menu item based on hover vs focus by keyboard. If it was a real `<button>`, we could use `:focus-visible {}` for that.

### Desired Behavior

Add a mechanism to style the menu item in a different way if it's reachable by keyboard, similar to `:focus-visible {}`

### Suggested Solution

Perhaps follow the current approach, adding a new selector (in a way that isn't breaking change):

```css
[data-reach-menu-item] { 
  background: white;
  color: black;
}

[data-reach-menu-item][data-selected] { 
  background: lightblue;
}

// NEW: Selector added only when the item is reached through keyboard.
[data-reach-menu-item][data-focus-visible] { 
  background: darkblue;
  color: white;
}

```

### Who does this impact? Who is this for?

I'd say this can be used by anyone and it improves the experience of people use mouse vs keyboard.

### Describe alternatives you've considered

N/A

### Additional context

N/A
